/*表空间*/
-- 需要修改DATAFILE路径
CREATE TABLESPACE OMS_BASE_TS LOGGING DATAFILE 'OMS_BASE_TS01.dbf' SIZE 2048M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED;
-- CREATE TABLESPACE OMS_BASE_IDX_TS LOGGING DATAFILE '\OMS_BASE_IDX_TS01.dbf' SIZE 2048M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED;


/*创建用户*/
DROP USER omsdb CASCADE;
CREATE USER omsdb PROFILE DEFAULT IDENTIFIED BY omsdb
DEFAULT TABLESPACE OMS_BASE_TS TEMPORARY TABLESPACE TEMP
ACCOUNT UNLOCK;

/*用户授权*/
--允许自动扩展空间(避免space空间不够的情况事务中断)
GRANT RESUMABLE TO omsdb;
--赋予用户查询权限
GRANT SELECT ANY SEQUENCE TO omsdb;
GRANT SELECT ANY TABLE TO omsdb;
--允许用户最大限度的使用表空间中的可用空间
GRANT UNLIMITED TABLESPACE TO omsdb;
--授予用户登录oracle权限
GRANT CONNECT TO omsdb;
--授予用户创建实体的权限
GRANT RESOURCE TO omsdb;
--若取消，Oracle 自带的Enterprice Manage Console无法登陆, 取消后不方便AMS后续运维。
GRANT SELECT_CATALOG_ROLE TO omsdb;
--授予用户创建视图的权限
GRANT CREATE VIEW TO omsdb;
--用于计划表分析时用
--GRANT EXECUTE ON  SYS.DBMS_STATS TO omsdb;
--GRANT EXECUTE ON  SYS.DBMS_LOCK TO omsdb;
--GRANT EXECUTE ON  SYS.DBMS_REPCAT_INTERNAL_PACKAGE TO omsdb;
--GRANT EXECUTE ON  SYS.DBMS_SNAPSHOT_UTL TO omsdb;
--GRANT EXECUTE ON  SYS.DBMS_LOGREP_UTIL TO omsdb;

COMMIT;